name: Upload Release Asset

on:
  repository_dispatch:
    types: [trigger-upload-artifact-workflow]  # This event type should match the one in the first workflow
permissions:
  contents: read    # Allows access to repository contents
  actions: read     # Allows reading and accessing workflow runs and artifacts

jobs:
  publish:
    name: Publish Release
    if: ${{ github.event.action == 'trigger-upload-artifact-workflow' }}
    runs-on: windows-2025

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.head_branch }}

      - name: Download artifact from previous workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: dotnet-desktop.yml
          name: built-artifact-Debug
          run_id: ${{ github.event.workflow_run.id }}
          path: ./artifact
          github_token: ${{ secrets.PAT_TOKEN }}  # Use the PAT here


      - name: Tag the commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag v1.2.3-intermediate ${{ github.event.workflow_run.head_sha }}
          git push origin v1.2.3-intermediate

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.2.3-intermediate
          release_name: Intermediate Release v1.2.3
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact/output-Debug.zip
          asset_name: my-app.zip
          asset_content_type: application/zip
